Trade functionality
palwashakmalik/zombie-apocalypse-survival pull request #15
Opened 2022-08-03 16:57 UTC by palwashamalik

2022-08-03 17:32 UTC, MishalNaeem requested changes

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/items_controller.rb
>    end
make this method private

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/items_controller.rb
> +  before_action :set_user
add empty line after that and use 
`before_action: set_user only:[index]`

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +    @trades = Trade.where('sender_id = ? OR receiver_id = ?', current_user.id, current_user.id)
define  scope for query

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +    @receiver_items = @user.items
use two separate private methods to set sender_items and receiver_items for user

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +    @trade = Trade.new(receiver_id: @user.id, sender_id: current_user.id)
no need to specify params here. New method is used to initialize the object like @trade=Trade.new

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +    @trade.accept if @trade.accepted?
refactor this code as accept is the status value.

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +  end
what is helpers means here? why we extract params here. you have to refactor this code

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +
make all these methods are private

2022-08-03 17:32 UTC, MishalNaeem commented on app/controllers/trades_controller.rb
> +  end
if you can permit two params here then how can you access params[:status] in update method?

2022-08-03 17:32 UTC, MishalNaeem commented on app/helpers/application_helper.rb
> +
make seperate files for helpers methods

2022-08-03 17:32 UTC, MishalNaeem commented on app/helpers/application_helper.rb
> +    [arr]
refactor this code as according to method name array is passing in location_array then why we need to check it

2022-08-03 17:32 UTC, MishalNaeem commented on app/helpers/application_helper.rb
> +  end
move these methods into model concerns

2022-08-03 17:32 UTC, MishalNaeem commented on app/models/trade.rb
> +    accepted!
refactor this code

2022-08-03 17:32 UTC, MishalNaeem commented on app/models/trade_item.rb
> +  belongs_to :item
add proper model level validations

2022-08-03 17:32 UTC, MishalNaeem commented on app/models/user.rb
> +  end
use scope instead of method

2022-08-03 17:32 UTC, MishalNaeem commented on app/models/user.rb
> +  end
irrelevant method as we can use it directly

2022-08-03 17:32 UTC, MishalNaeem commented on app/views/items/index.html.erb
> +<%if !@user.eql?(current_user)%>
use unless instead of if and negation

2022-08-03 17:32 UTC, MishalNaeem commented on app/views/layouts/application.html.erb
> +    <% if current_user and !current_user.admin%>
use current_user.admin? instead of negation sign

2022-08-03 17:32 UTC, MishalNaeem commented on config/routes.rb
>    root 'home#index'
move this route at the end of the file

2022-08-03 17:32 UTC, MishalNaeem commented on config/routes.rb
>        put 'unlike' => 'users#downvote'
use symbols instead of string

2022-08-03 17:32 UTC, MishalNaeem commented on config/routes.rb
> +    resources :items
specify actions for trade_items and items resources

2022-08-03 17:32 UTC, MishalNaeem commented on config/routes.rb
> +  resources :trades, only: :update
duplication. remove this one and use single resource for trades model

2022-08-03 17:32 UTC, MishalNaeem commented on db/migrate/20220728161329_create_trades.rb
> +      t.integer :status, default: 0
use enum for status instead of integer

2022-08-03 17:32 UTC, MishalNaeem commented on db/migrate/20220725115013_change_infected_in_users.rb
> +    change_column :users, :infected, :integer, using: 'infected::integer'
use boolean instead of integer

2022-08-03 17:32 UTC, MishalNaeem commented on db/migrate/20220729054302_add_trade_to_trade_items.rb
> +end
rollback this migration and add this column in trade items migration and make it single

2022-08-03 17:32 UTC, MishalNaeem commented on db/schema.rb
rebasing issues kindly resolve these

2022-08-03 17:32 UTC, MishalNaeem commented on test/models/trade_history_test.rb
> +end
delete this file too

2022-08-03 17:32 UTC, MishalNaeem commented on test/models/trade_item_test.rb
> +end
delete this file and tmp files

2022-08-04 00:48 UTC, palwashamalik commented on db/migrate/20220725115013_change_infected_in_users.rb
> +    change_column :users, :infected, :integer, using: 'infected::integer'
I have its updated in next migration and in schema file t.boolean "infected", default: false

2022-08-05 07:44 UTC, MishalNaeem approved these changes

2022-08-05 07:57 UTC, merged